version: '3'
services:
  postgres:
      image: postgres
      volumes:
          - ./sql/init_001.sql:/docker-entrypoint-initdb.d/1-init.sql
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=1211
          - POSTGRES_DB=postgres
      ports:
          - 5432
      networks:
        - db_nw

#  redis:
#    image: redis:4
#    ports:
#        - 6379:6379
  web:
    build: ./
    ports:
      - 8080:8080
    links:
      - postgres
#      - redis
    networks:
      - db_nw
      - web_nw

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge